name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Use the node version compatible with your project
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
        # This will run the "build" script in your package.json which should be configured to use Vite to build the project
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './dist' # Make sure this points to the directory where Vite outputs the production build
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
